--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 01. 03. 23:05:07
-- Server version: 5.5.5-10.4.24-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS cars;

CREATE DATABASE IF NOT EXISTS cars
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE cars;

DELIMITER $$

--
-- Create function `randomInteger`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS randomInteger(start INT, end INT)
  RETURNS int(11)
BEGIN

RETURN FLOOR( RAND() * (end-start+1) + start);
END
$$

--
-- Create function `randomRendszam`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS randomRendszam(carName varchar(255))
  RETURNS varchar(255) CHARSET utf8 COLLATE utf8_hungarian_ci
BEGIN
  declare b varchar(255);
  set b = UPPER(LEFT(carName,2));
RETURN concat(b,"-",randomInteger(1000,2000));
END
$$

--
-- Create function `randomAuto`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION IF NOT EXISTS randomAuto()
  RETURNS varchar(255) CHARSET utf8 COLLATE utf8_hungarian_ci
BEGIN

RETURN ELT(randomInteger(1,3),"Mercedesz","Fiat","BMW");
END
$$

DELIMITER ;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `cars`
--
CREATE TABLE IF NOT EXISTS cars (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  licenceNumber VARCHAR(255) DEFAULT NULL,
  hourlyRate INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `trips`
--
CREATE TABLE IF NOT EXISTS trips (
  id INT(11) NOT NULL AUTO_INCREMENT,
  numberOfMinits INT(11) DEFAULT NULL,
  date DATETIME DEFAULT NULL,
  carId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 44,
AVG_ROW_LENGTH = 468,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `IDX_trips_carId` on table `trips`
--
ALTER TABLE trips 
  ADD INDEX IDX_trips_carId(carId);

--
-- Create foreign key
--
ALTER TABLE trips 
  ADD CONSTRAINT FK_trips_cars_id FOREIGN KEY (carId)
    REFERENCES cars(id);

DELIMITER $$

--
-- Create procedure `tesztAdatokKezi`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE tesztAdatokKezi()
BEGIN

DELETE
  FROM trips;
DELETE
  FROM cars;
DELETE
  FROM users;

INSERT cars (id, name, licenceNumber, hourlyRate)
  VALUES (1, 'Mercedes', 'MM-111', 2000), (2, 'Fiat', 'FF-111', 2100), (3, 'BMW', 'BB-111', 2200);

INSERT trips (id, numberOfMinits, date, carId)
  VALUES (1, 25, '2022.10.13 12:20:00', 1), (2, 35, '2022.10.13 13:30:00', 1), (3, 20, '2022.10.13 14:20:00', 1),
  (4, 25, '2022.10.13 12:30:00', 2), (5, 15, '2022.10.13 13:40:00', 2),
  (6, 30, '2022.10.13 12:10:00', 3), (7, 15, '2022.10.13 14:30:00', 3), (8, 25, '2022.10.13 15:10:00', 3);

INSERT users (id, email, password)
  VALUES (1, 'jozsi@gmail.com', 'jozsijelszo'), (2, 'bela@gmail.com', 'belajelszo'), (3, 'feri@gmail.com', 'ferijelszo');

# Lekérdezések
SELECT
  *
FROM cars;
SELECT
  *
FROM trips;
SELECT
  *
FROM users;

END
$$

--
-- Create procedure `tesztAdatokAutomata`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE tesztAdatokAutomata(carCount int, dateValue varchar(255), tripCountMin INT, tripCountMax INT)
BEGIN

DELETE
  FROM trips;
DELETE
  FROM cars;
DELETE
  FROM users;

SET @a = 0;


auto_loop: LOOP
  SET @a=@a+1;

  # Autók generálása
  SET @carId = @a;
  SET @rAuto = randomAuto();
INSERT cars (id, name, licenceNumber, hourlyRate)
  VALUES (@carId, @rAuto, randomRendszam(@rAuto), randomInteger(2000, 3000));
    
  #trip-ek 
  SET @t = 0;
  SET @deltaMinits = 0;
  SET @tripCount = randomInteger(tripCountMin, tripCountMax);
  trip_loop: LOOP 
    SET @t = @t + 1;
    SET @numberOfMinits = randomInteger(15,60);
    SET @pauseMinits = randomInteger(0,60);
    SET @deltaMinits = @deltaMinits + @numberOfMinits +  @pauseMinits;
    SET @date = TIMESTAMPADD(MINUTE, @deltaMinits, datevalue);

# Egy trip
INSERT trips (numberOfMinits, date, carId)
  VALUES (@numberOfMinits, @date, @carId);

    IF @t=@tripCount THEN
      LEAVE trip_loop;
    END IF;
  END LOOP trip_loop;
   
  IF @a=carCount THEN
    LEAVE auto_loop;
  END IF;
END LOOP auto_loop;

# Users
INSERT users (id, email, password)
  VALUES (1, 'jozsi@gmail.com', 'jozsijelszo'), (2, 'bela@gmail.com', 'belajelszo'), (3, 'feri@gmail.com', 'ferijelszo');

# Lekérdezések
SELECT
  *
FROM cars;
SELECT
  *
FROM trips;
SELECT
  *
FROM users;


END
$$

DELIMITER ;

-- 
-- Dumping data for table cars
--
INSERT INTO cars VALUES
(1, 'BMW', 'BM-1928', 2810),
(2, 'Mercedesz', 'ME-1429', 2619),
(3, 'BMW', 'BM-1868', 2559),
(4, 'Mercedesz', 'ME-1935', 2646),
(5, 'Mercedesz', 'ME-1535', 2224),
(6, 'Mercedesz', 'ME-1904', 2698),
(7, 'BMW', 'BM-1151', 2387),
(8, 'Mercedesz', 'ME-1955', 2905),
(9, 'BMW', 'BM-1070', 2646),
(10, 'Fiat', 'FI-1718', 2370);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'jozsi@gmail.com', 'jozsijelszo'),
(2, 'bela@gmail.com', 'belajelszo'),
(3, 'feri@gmail.com', 'ferijelszo');

-- 
-- Dumping data for table trips
--
INSERT INTO trips VALUES
(9, 56, '2022-10-13 13:36:00', 1),
(10, 46, '2022-10-13 14:45:00', 1),
(11, 54, '2022-10-13 15:48:00', 1),
(12, 23, '2022-10-13 12:52:00', 2),
(13, 54, '2022-10-13 14:37:00', 2),
(14, 45, '2022-10-13 16:10:00', 2),
(15, 60, '2022-10-13 17:43:00', 2),
(16, 50, '2022-10-13 18:48:00', 2),
(17, 28, '2022-10-13 13:22:00', 3),
(18, 43, '2022-10-13 14:27:00', 3),
(19, 23, '2022-10-13 13:04:00', 4),
(20, 54, '2022-10-13 14:12:00', 4),
(21, 43, '2022-10-13 15:19:00', 4),
(22, 56, '2022-10-13 13:56:00', 5),
(23, 24, '2022-10-13 14:23:00', 5),
(24, 47, '2022-10-13 15:32:00', 5),
(25, 48, '2022-10-13 16:49:00', 5),
(26, 51, '2022-10-13 13:32:00', 6),
(27, 59, '2022-10-13 15:18:00', 6),
(28, 15, '2022-10-13 16:18:00', 6),
(29, 45, '2022-10-13 17:09:00', 6),
(30, 38, '2022-10-13 18:03:00', 6),
(31, 25, '2022-10-13 13:10:00', 7),
(32, 16, '2022-10-13 14:19:00', 7),
(33, 28, '2022-10-13 15:37:00', 7),
(34, 41, '2022-10-13 13:37:00', 8),
(35, 55, '2022-10-13 15:13:00', 8),
(36, 46, '2022-10-13 16:26:00', 8),
(37, 22, '2022-10-13 17:17:00', 8),
(38, 21, '2022-10-13 13:03:00', 9),
(39, 16, '2022-10-13 13:25:00', 9),
(40, 31, '2022-10-13 13:16:00', 10),
(41, 43, '2022-10-13 14:51:00', 10),
(42, 34, '2022-10-13 16:00:00', 10),
(43, 43, '2022-10-13 17:01:00', 10);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;